okhv = "OKH-LOSHv1.0"
name = "The Greenest Solar Power? Life Cycle Assessment of Foam-Based Flexible Floatovoltaics"
repo = "https://www.appropedia.org/The_Greenest_Solar_Power?_Life_Cycle_Assessment_of_Foam-Based_Flexible_Floatovoltaics"
version = "7"
license = "CC-BY-SA-4.0"
licensor = ". Joshua M. Pearce"
upload-method = "manifest-script"
image = ["https://www.appropedia.org/w/images/a/a2/Greensun.png"]
documentation-language = "en"
timestamp = "1650188561"
function = "This study presents a life cycle analysis (LCA) of a 10-MW foam-based floatovoltaics (FPV) plant installed on Lake Mead, Nevada, U.S. A material inventory of the flexible crystalline silicon (c-Si)-based module involved massing and determination of material composition of the moduleâ€™s encapsulation layers with ATR/FTR spectroscopy and electron microscopy. The LCA was performed using SimaPro and the results were interpreted in terms of cumulative energy demands, energy payback time, global warming potential, GHG emissions, and water footprint including negative values for reduced evaporation. A sensitivity analysis was performed on the lifetime of the modules and the foam-based racking. The results show 30-year lifetime foam-based FPV system have one of the lowest energy payback times (1.3 years) and the lowest GHG emissions to energy ratio (11 kg CO2 eq/MWh) in c-Si solar PV technologies reported to date. In addition, the foam-based FPV system also had 5 times less water footprint (21.5 m3/MWh) as compared to a conventional pontoon-based FPV (110 m3/MWh)."
documentation-readiness-level = "ODRL-1"
technology-readiness-level = "OTRL-1"
